classes:
- system.linux.system.repo.mcp.salt
- system.linux.system.repo.mcp.extra
- system.linux.system.repo.ubuntu
- system.linux.system.repo.glusterfs
- system.openssh.client.lab
- system.glusterfs.client.cluster
- system.glusterfs.client.volume.salt_pki
- system.salt.master.pkg
- system.salt.minion.ca.salt_master
- system.salt.master.api
- system.reclass.storage.salt
- system.xtrabackup.server.single
- system.reclass.storage.system.physical_control_cluster
- system.reclass.storage.system.openstack_gateway_cluster
- system.reclass.storage.system.openstack_control_cluster
- system.reclass.storage.system.openstack_proxy_cluster
- system.reclass.storage.system.openstack_database_cluster
- system.reclass.storage.system.openstack_message_queue_cluster
- cluster.mcp11-neutron-dpdk.infra
parameters:
  _param:
    salt_master_base_environment: prd
    reclass_data_repository: "https://github.com/AKamyshnikova/mcp-scale-nfv-model.git"
    reclass_data_revision: master
    reclass_config_master: ${_param:infra_config_deploy_address}
    single_address: ${_param:infra_config_address}
    deploy_address: ${_param:infra_config_deploy_address}
    linux_system_codename: xenial
    salt_api_password_hash: "<<WILL_BE_GENERATED>>"
    salt_master_host: ${_param:infra_config_address}
  reclass:
    storage:
      node:
        infra_kvm_node01:
          params:
            keepalived_vip_priority: 100
            linux_system_codename: xenial
        infra_kvm_node02:
          params:
            keepalived_vip_priority: 101
            linux_system_codename: xenial
        infra_kvm_node03:
          params:
            keepalived_vip_priority: 102
            linux_system_codename: xenial
        openstack_control_node01:
          params:
            linux_system_codename: xenial
          classes:
          - cluster.${_param:cluster_name}.openstack.control_init
        openstack_control_node02:
          params:
            linux_system_codename: xenial
        openstack_control_node03:
          params:
            linux_system_codename: xenial
        openstack_database_node01:
          params:
            linux_system_codename: xenial
          classes:
          - cluster.${_param:cluster_name}.openstack.database_init
        openstack_database_node02:
          params:
            linux_system_codename: xenial
        openstack_database_node03:
          params:
            linux_system_codename: xenial
        openstack_message_queue_node01:
          params:
            linux_system_codename: xenial
        openstack_message_queue_node02:
          params:
            linux_system_codename: xenial
        openstack_message_queue_node03:
          params:
            linux_system_codename: xenial
        openstack_proxy_node01:
          params:
            linux_system_codename: xenial
        openstack_gateway_node01:
          name: gtw01
          domain: ${_param:cluster_domain}
          classes:
          - cluster.${_param:cluster_name}.openstack.gateway
          params:
            salt_master_host:  ${_param:reclass_config_master}
            single_address: ${_param:openstack_gateway_node01_address}
            tenant_address: ${_param:openstack_gateway_node01_tenant_address}
            deploy_address: ${_param:openstack_gateway_node01_deploy_address}
            linux_system_codename: xenial
        openstack_gateway_node02:
          name: gtw02
          domain: ${_param:cluster_domain}
          params:
            salt_master_host:  ${_param:reclass_config_master}
            single_address: ${_param:openstack_gateway_node02_address}
            tenant_address: ${_param:openstack_gateway_node02_tenant_address}
            deploy_address: ${_param:openstack_gateway_node02_deploy_address}
            linux_system_codename: xenial
        openstack_gateway_node03:
          name: gtw03
          domain: ${_param:cluster_domain}
          classes:
          - cluster.${_param:cluster_name}.openstack.gateway
          params:
            salt_master_host:  ${_param:reclass_config_master}
            single_address: ${_param:openstack_gateway_node03_address}
            tenant_address: ${_param:openstack_gateway_node03_tenant_address}
            deploy_address: ${_param:openstack_gateway_node03_deploy_address}
            linux_system_codename: xenial
        openstack_compute_rack01:
          name: ${_param:openstack_compute_rack01_hostname}<<count>>
          domain: ${_param:cluster_domain}
          classes:
          - cluster.${_param:cluster_name}.openstack.compute.dpdk
          repeat:
            count: 90
            start: 1
            digits: 3
            params:
              single_address:
                value: ${_param:openstack_compute_rack01_single_subnet}.<<count>>
                start: 10
              tenant_address:
                value: ${_param:openstack_compute_rack01_tenant_subnet}.<<count>>
                start: 10
              deploy_address:
                value: ${_param:openstack_compute_rack01_deploy_subnet}.<<count>>
                start: 10
          params:
            salt_master_host: ${_param:reclass_config_master}
            linux_system_codename: xenial
#            dpdk0_name: enp5s0f1
#            dpdk1_name: enp5s0f2
#            dpdk0_pci: '"0000:05:00.1"'
#            dpdk1_pci: '"0000:05:00.2"'
#            compute_dpdk_driver: uio
#            compute_ovs_pmd_cpu_mask: "0x6"
#            compute_ovs_dpdk_socket_mem: "1024"
#            compute_ovs_dpdk_lcore_mask: "0x400"
#            compute_ovs_memory_channels: "2"
