
classes:
- system.linux.system.single
- system.openssh.server.team.lab
- system.openssh.server.team.mcp_qa
- system.openssh.server.team.networking
- system.openssh.server.team.qa_scale
- cluster.mcp11-neutron-dpdk.openstack

parameters:
  _param:
    salt_control_trusty_image: http://apt-mk.mirantis.com/images/ubuntu-14-04-x64-mcp1.1.qcow2
    salt_control_xenial_image: http://apt-mk.mirantis.com/images/ubuntu-16-04-x64-mcp1.1.qcow2
    infra_config_hostname: cfg01
    salt_minion_ca_host: ${_param:infra_config_hostname}.${_param:cluster_domain}
    # infra service addresses
    infra_config_address: 10.3.56.9
    infra_config_deploy_address: 10.10.0.2

    cluster_domain: mcp11-neutron-dpdk.local
    cluster_name: mcp11-neutron-dpdk
    cluster_public_host: ${_param:openstack_proxy_address}
    control_network_netmask: 255.255.248.0
    tenant_network_netmask: 255.255.255.0

    dns_server01: 8.8.8.8
    dns_server02: 8.8.4.4
    control_vlan: 130
    tenant_vlan: 132

    deploy_network_netmask: 255.255.0.0
    deploy_network_gateway: 10.10.0.52


    infra_kvm_address: 10.167.4.240
    infra_kvm_node01_address: 10.3.56.136
    infra_kvm_node02_address: 10.3.56.144
    infra_kvm_node03_address: 10.3.56.181
    infra_kvm_node01_deploy_address: 10.10.56.136
    infra_kvm_node02_deploy_address: 10.10.56.144
    infra_kvm_node03_deploy_address: 10.10.56.181
    infra_kvm_node01_hostname: kvm01
    infra_kvm_node02_hostname: kvm02
    infra_kvm_node03_hostname: kvm03

    glusterfs_node01_address: ${_param:infra_kvm_node01_address}
    glusterfs_node02_address: ${_param:infra_kvm_node02_address}
    glusterfs_node03_address: ${_param:infra_kvm_node03_address}

    linux_dhcp_interface:
      enabled: true
      type: eth
      proto: dhcp
    linux_single_interface:
      enabled: true
      type: eth
      proto: static
      address: ${_param:single_address}
      netmask: ${_param:control_network_netmask}
      name_servers:
        - ${_param:dns_server01}
        - ${_param:dns_server02}


  salt:
    minion:
      trusted_ca_minions:
        - ${_param:salt_minion_ca_host}

  linux:
    network:
      host:
        cfg01:
          address: ${_param:infra_config_address}
          names:
          - ${_param:infra_config_hostname}
          - ${_param:infra_config_hostname}.${_param:cluster_domain}
        cfg:
          address: ${_param:infra_config_address}
          names:
          - cfg
          - cfg.${_param:cluster_domain}
        kvm01:
          address: ${_param:infra_kvm_node01_address}
          names:
          - ${_param:infra_kvm_node01_hostname}
          - ${_param:infra_kvm_node01_hostname}.${_param:cluster_domain}
        kvm02:
          address: ${_param:infra_kvm_node02_address}
          names:
          - ${_param:infra_kvm_node02_hostname}
          - ${_param:infra_kvm_node02_hostname}.${_param:cluster_domain}
        kvm03:
          address: ${_param:infra_kvm_node03_address}
          names:
          - ${_param:infra_kvm_node03_hostname}
          - ${_param:infra_kvm_node03_hostname}.${_param:cluster_domain}
    system:
      name: ${_param:infra_config_hostname}
      domain: ${_param:cluster_domain}
      service:
        apt-daily.timer:
          status: dead
      user:
        root:
          enabled: true
          name: root
          home: /root
          # Password is cloudlab, comment out, configure your SSH key bellow
          # and disable password auth
          password: $6$0Qqj.6l.$T9k9Onm9pIDo6ULABVBRNogyizG.9CnwQ4bvI4xH.AWeIGHbLyFU87ejMTtKvAAyd3dncRYbeUV.VbnXJU2u./

